spring:
  application:
    name: ${spring.application.name}
  profiles:
    active: dev

server:
  port: ${server.port}

logging:
  level:
    root: ${logging.level.root}

comradexy:
  middleware:
    scheudle:
      schedulerServerId: ${comradexy.middleware.scheudle.schedulerServerId}
      schedulerServerName: ${comradexy.middleware.scheudle.schedulerServerName}
      schedulerPoolSize: ${comradexy.middleware.scheudle.schedulerPoolSize}
      enableStorage: ${comradexy.middleware.scheudle.enableStorage}
      enableAdmin: ${comradexy.middleware.scheudle.enableAdmin}
      storageType: ${comradexy.middleware.scheudle.storageType}
      dataSource:
        url: ${comradexy.middleware.scheudle.dataSource.url}
        username: ${comradexy.middleware.scheudle.dataSource.username}
        password: ${comradexy.middleware.scheudle.dataSource.password}
