server:
  port: 8091

# 设置日志级别
logging:
  level:
    root: info

comradexy:
  middleware:
    scheudle:
      schedulerServerId: easy-cron-scheduler-server-01
      schedulerServerName: 简易定时任务调度服务01
      schedulerPoolSize: 8
      enableStorage: false
